export enum CardErrorCode {
  CARD_NOT_FOUND = "CARD_NOT_FOUND",
  CARD_NAME_TAKEN = "CARD_NAME_TAKEN",
  CARD_FETCH_FAILED = "CARD_FETCH_FAILED",
  CARD_CREATE_FAILED = "CARD_CREATE_FAILED",
  CARD_UPDATE_FAILED = "CARD_UPDATE_FAILED",
  CARD_DELETE_FAILED = "CARD_DELETE_FAILED",
}
