export enum ExpenseErrorCode {
  EXPENSE_NOT_FOUND = "EXPENSE_NOT_FOUND",
  EXPENSE_FETCH_FAILED = "EXPENSE_FETCH_FAILED",
  EXPENSE_CREATE_FAILED = "EXPENSE_CREATE_FAILED",
  EXPENSE_UPDATE_FAILED = "EXPENSE_UPDATE_FAILED",
  EXPENSE_DELETE_FAILED = "EXPENSE_DELETE_FAILED",
}
