export enum SalaryErrorCode {
  SALARY_NOT_FOUND = "SALARY_NOT_FOUND",
  SALARY_FETCH_FAILED = "SALARY_FETCH_FAILED",
  SALARY_CREATE_FAILED = "SALARY_CREATE_FAILED",
  SALARY_UPDATE_FAILED = "SALARY_UPDATE_FAILED",
  SALARY_DELETE_FAILED = "SALARY_DELETE_FAILED",
}
