export enum StatementErrorCode {
  STATEMENT_NOT_FOUND = "STATEMENT_NOT_FOUND",
  CARD_NOT_FOUND = "CARD_NOT_FOUND",
  STATEMENT_FETCH_FAILED = "STATEMENT_FETCH_FAILED",
  STATEMENT_SAVE_FAILED = "STATEMENT_SAVE_FAILED",
  STATEMENT_DELETE_FAILED = "STATEMENT_DELETE_FAILED",
}
